ALTER TABLE sellers 
  ADD COLUMN IF NOT EXISTS telegram_report_time TIME DEFAULT '09:00:00',
  ADD COLUMN IF NOT EXISTS notification_sound BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS notification_browser BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
